[package]
name = "mpu-6050-test"
version = "0.1.0"
authors = ["Rachel Domagalski <rsdomagalski@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33"
i2cdev = "0.4"
linux-embedded-hal = "0.3"
mpu6050 = "0.1.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
